### ISSUE TITLE
Handling individuals

### ISSUE THREAD

**Issue by loopasam** [loopasam/Brain#1]
The OWL individuals are not handled at the moment.

**Comment by dosumis** [comment]
We'd certainly use this in VFB if it were available.  Note, we require support for class expressions that name individuals.  For example, this query finds members of a cluster individual neurons where membership of the cluster is  defined by similarity to an exemplar individual (neuron).

 'member_of' some ('has_exemplar' value <neuron name>)

**Comment by loopasam** [comment]
I will implement this soon (coming month), it shouldn't be too difficult and all OWL entity types will then be supported.

**Comment by dosumis** [comment]
Hi Samuel,

Wondering if you still plan to add this functionality.

Cheers,
David

Note - despite my previous comment - very useful even without implementation of a system for using labels in class expressions.

**Comment by loopasam** [comment]
Hi David,

Individual supports (add/remove + ABox realisation via ELK) is finally coming end of next week for the release of the 1.4.2. Hope you can wait till then!

Samuel

**Comment by dosumis** [comment]
Thanks!
