### ISSUE TITLE
getAnnotations()

### ISSUE THREAD

**Issue by loopasam** [loopasam/Brain#10]
Request to be able to retrieve the array of annotations

**Comment by dosumis** [comment]
Related request:   

getAnnotation() currently returns a string.  When there are multiple annotations using the same annotationProperty, this string consists of one of the annotationProperty chosen seemingly at random.  Given that it is always possible for an OWLEntity to be annotated with multiple annotationProperty axioms using the same annotationProperty, getAnnotation() should return an array.

**Comment by dosumis** [comment]
Wondering if you could make fixing this one a high priority, as it is blocking adoption by GO for basic scripting.

**Comment by loopasam** [comment]
A new method was created to retrieve the value of all annotations: `getAnnotations("entity", "annotationProperty")`. The feature is part of the [release 1.5.1](https://github.com/loopasam/Brain/wiki/Releases#wiki-15---march-2014). More info in the [documentation](https://github.com/loopasam/Brain/wiki/Examples#wiki-aproperties).
