### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by dosumis** [loopasam/Brain#12]
Could you add documentation for how to convert a Brain object into one that can be used with OWL-API methods?

**Comment by dosumis** [comment]
Worked it out from javadoc.  Brain.getOntology.  Still, might be good to have in general doc too.

**Comment by loopasam** [comment]
I've updated the wiki with the information: https://github.com/loopasam/Brain/wiki/Examples#access-to-owl-api-methods

Good like this, you think?

**Comment by dosumis** [comment]
Perfect
